### ISSUE TITLE
[bug] Latest master is not respecting DRF requirement

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#244]
The latest master is pulling a more recent version of DRF than what's specified in the dependencies.

This causes a bug in `admin.py`:

```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/.virtualenvs/openwisp-radius/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/.virtualenvs/openwisp-radius/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/.virtualenvs/openwisp-radius/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/.virtualenvs/openwisp-radius/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/.virtualenvs/openwisp-radius/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/.virtualenvs/openwisp-radius/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/.virtualenvs/openwisp-radius/lib/python3.8/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Code/openwisp/openwisp-radius/openwisp_radius/admin.py", line 636, in <module>
    admin.site.unregister(Token)
  File "/.virtualenvs/openwisp-radius/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 146, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model Token is not registered
```

To replicate just clone the repo, install the dependencies with `pip install -e .` and try running `./manage.py migrate`.

We should understand what is causing a more recent version of DRF to be pulled, because even if we solve this specific issue we will have more issues in the future whenever new versions of DRF are released.
We need to ensure the DRF requirement we specify is respected.

Then to add support for a more recent version of DRF we already have: https://github.com/openwisp/openwisp-radius/pull/203.

**Comment by nemesisdesign** [comment]
For whoever incurs into this bug, the workaround is the following:

```
# ensure our python virtualenv is enabled
pip install --upgrade "djangorestframework>=3.11,<3.12"
```

**Comment by ManishShah120** [comment]
@nemesisdesign I would love to work on this issue.

**Comment by nemesisdesign** [comment]
@ManishShah120 I was already trying a fix, I found out that the new pip dependency resolution algorithm fixes this particular issue: https://github.com/openwisp/openwisp-radius/pull/245.

The more recent DRF dependency is being pulled from dj-rest-auth when using pip <= 20.4.
