### ISSUE TITLE
[bug] Captive portal login mock fails to create accounting for phone number change

### ISSUE THREAD

**Issue by codesankalp** [openwisp/openwisp-radius#367]
Accounting session is not created if the phonenumber is changed.

```python
[23/Jan/2022 16:47:30,344] Captive portal login mock view called with: <QueryDict: {'auth_user': ['+919876543210'], 'auth_pass': ['DaPPLlKrbQGbfH3FSUvw4OFLhVYxqwYLpAHKjEjY']}>
Internal Server Error: /api/v1/freeradius/accounting/
Traceback (most recent call last):
  File "/home/sankalp/Desktop/op-wifi/openwisp-radius/openwisp_radius/api/freeradius_views.py", line 428, in post
    instance = self.get_queryset().get(unique_id=data.get('unique_id'))
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
openwisp_radius.models.RadiusAccounting.DoesNotExist: RadiusAccounting matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sankalp/Desktop/op-wifi/openwisp-radius/openwisp_radius/api/freeradius_views.py", line 432, in post
    acct_data = self._data_to_acct_model(serializer.validated_data.copy())
  File "/home/sankalp/Desktop/op-wifi/openwisp-radius/openwisp_radius/api/freeradius_views.py", line 446, in _data_to_acct_model
    acct_org = Organization.objects.get(pk=self.request.auth)
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sankalp/Desktop/op-wifi/venv/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
openwisp_users.models.Organization.DoesNotExist: Organization matching query does not exist.
[23/Jan/2022 16:47:30] "POST /api/v1/freeradius/accounting/ HTTP/1.1" 500 143298
```

**Comment by nemesisdesign** [comment]
The analysis of the issue is incorrect. Please see https://github.com/openwisp/openwisp-radius/issues/369.
