### ISSUE TITLE
./manage.py migrate raises exception

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#7]
```
./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 79, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/loader.py", line 268, in build_graph
    raise exc
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/loader.py", line 242, in build_graph
    self.graph.validate_consistency()
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/graph.py", line 243, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/graph.py", line 243, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/graph.py", line 96, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration openwisp_radius.0001_initial dependencies reference nonexistent parent node ('openwisp_users', '0002_auto_20180725_2359')
```

**Comment by rohithasrk** [comment]
@nemesisdesign I've encountered this issue as well. I've observed that a migration file is generated in openwisp-users whenever we try to run the migration. Could it be that openwisp-users has some migration files missing?
