### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#8]
Calling `./runtests.py` fails:

```
./runtests.py --keepdb
Using existing test database for alias 'default'...
System check identified no issues (0 silenced).
E
======================================================================
ERROR: openwisp_radius.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: openwisp_radius.tests
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/nemesis/Code/openwisp-radius/openwisp_radius/tests.py", line 7, in <module>
    from django_freeradius.tests import FileMixin
ImportError: cannot import name 'FileMixin'

```

**Comment by nemesisdesign** [comment]
False alarm, I hadn't updated `django-freeradius` to the latest master
